DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS role;

CREATE TABLE employee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30),
 );

 CREATE TABLE department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30)
 );

 CREATE TABLE role (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    tile VARCHAR(30),
    salary DECIMAL,
    department_id REFERENCES department(id) ON DELETE SET NULL
 )